spring.datasource.url=jdbc:mysql://localhost:3306/medical_system
spring.datasource.username=root
spring.datasource.password=2400031677

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect